test failure

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -7,9 +7,12 @@ jobs:
         steps:
             - name: Step 1
               run: sleep 20
+            - name: Step 2
+              id: step-2
+              run: exit 1
             - name: Runs on Failure
-              if: failure()
-              run: echo "Runs only on failure"
+              if: failure() && steps.step-2.conclusion == 'failure'
+              run: echo "Runs only on step 2 has failure"
             - name: Runs on Success
               # Success is not needed because it is the default behavior
               if: success()
